create database BookManagment;
use  BookManagment;

desc books;
desc customers;
desc orders;

select* from books;
select * from customers;
select * from orders;

-- 1 Retrive all books in Fiction Genere?

select *
from books
where Genre ="Fiction";

-- 2 Find books after publish year 1950

select *
from books
where published_year > 1950;

-- 3 All customer from canada
select * 
from customers
where Country like '%Canada%';

-- 4 Show order placed in nov 2023
 select *
 from orders
 where month(Order_Date) = "11" and year(order_date)='2023';
 
 -- 5 Retrive total stock from books available
 select count(*) as "book"
 from books;
 
 -- 6 Find most expensive books
 select title,genre, max(price) as "Most_expensive"
 from books
 group by title,genre
 order by most_expensive desc
 ;
 
 -- 7 Show all customer who orderd more than 1 quantity of book
 
select order_id, customer_id,book_id,quantity
 from orders
 having quantity > 1;
 
 -- 8 Retrive all orders where the total amount exceeds 150
 
select total_amount
from orders
where total_amount > 150;

-- 9 List all genre available in the books
select genre,count(*) as "total_count"
from books
group by genre;
 
-- 10 Find the books with lowest stock
select book_id ,title,min(stock) as "Lowest_stock"
from books
group by book_id,title
order by lowest_stock asc;

-- 11 Calculate total revenue generated by all orders
select sum(o.quantity*b.price) as "total_revenu"
from orders o 
join books b 
on o.book_id=b.book_id
;

-- 12 Retrive total number of books sold by which genre

select Genre ,sum(o.quantity) as "total_book_sold"
from orders o
join books b 
on o.book_id=b.book_id
group by genre;


-- 13 Find avg price of books in fantasy genre
select round(avg(price),2) as "avg_price"
from books
where genre like "%fantasy%"
;

-- 14 List customer who have place atleast 2 orders
select c.customer_id,c.name ,count(o.order_id) as "count_order"
from customers c
join orders o
on c.customer_id=o.customer_id
group by  c.customer_id,c.name
having count(o.order_id) =2
;

-- 15 Find most frequently order book
select book_id,count(*) as "most_frequently" 
from orders
group by book_id
order by most_frequently desc limit 1;

-- 16 Show the top 3 most expensive books of fantasy genre
select title,max(price)  as "most_expensive"
from books
group by title
order by most_expensive desc limit 3;

-- 17 Retrive total quantity of books sold by each author

select b.author,sum(o.quantity) as "book_sold"
from books b
join orders o 
on b.book_id=o.book_id
group by b.author
;

-- 18 List the cities where customers who spent over $30 located 

select distinct c.city, o.total_amount
from orders o 
join customers c 
on o.customer_id=c.customer_id
where o.total_amount > 30;

-- 19 Find the customer who spent most on orders
select c.name,sum(o.total_amount)as 'count_order' 
from customers c
join orders o 
on c.customer_id= o.customer_id
group by c.name
order by count_order desc limit 1;

-- 20 Calculate stock remaining after fullfiling all orders
select b.book_id,b.title,b.stock,
		coalesce(sum(o.quantity),0) as order_quantity,
        b.stock - coalesce(sum(o.quantity),0) as remaining_quantity
from books b
left join orders o 
on b.book_id=o.book_id
group by b.book_id,b.title,b.stock
order by b.book_id;